version: '3.0'
services:
  # frontend:
  # backend:
  # sender:
  #   build: './mail-sender'
  #   environment:
  #     - NODE_ENV=docker
  #   depends_on:
  #     - mongodb
  #     - etcd
  mongodb:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - './common/mongodata:/mongodata'
  etcd:
    image: quay.io/coreos/etcd
    ports:
      - '2379:2379'
      - '2380:2380'
    volumes:
      - './common/etcd-data:/etcd-data'
    command:
      - /usr/local/bin/etcd
      - -name
      - etcd
      - --data-dir
      - /etcd_data
      - -advertise-client-urls
      - http://etcd:2379
      - -listen-client-urls
      - http://0.0.0.0:2379
      - -initial-advertise-peer-urls
      - http://etcd:2380
      - -listen-peer-urls
      - http://0.0.0.0:2380
      - -initial-cluster
      - etcd=http://etcd:2380