version: '3.0'
services:
  # frontend:
  # backend:
  sender:
    build: '../mail-sender'
    environment:
      - NODE_ENV=docker
    depends_on:
      - mongodb
      # - redis
  mongodb:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - './mongodata:/mongodata'
  etcd:
    image: quay.io/coreos/etcd
    ports:
      - '2379:2379'
      - '2380:2380'
    volumes:
      - './etcd-data:/etcd-data'
  redis:
    image: redis
    ports:
      - '6379:6379'